import {groq} from 'next-sanity'

export const landingPageQuery = groq`
  *[_type == "landingPage" && _id == "landingPage"][0]{
    seo{
      title,
      description,
      ogTitle,
      ogDescription,
      canonicalUrl,
      ogImage{
        alt,
        image
      }
    },
    navbar{
      brandName,
      links[]{
        label,
        href
      },
      ctaText,
      ctaHref
    },
    hero{
      eyebrow,
      title,
      highlightedText,
      description,
      subDescription,
      tags[],
      ctaText,
      ctaHref,
      disclaimer,
      formEyebrow,
      formTitle,
      formDescription
    },
    proofStats[]{
      stat,
      label
    },
    problem{
      intro{
        eyebrow,
        title,
        intro
      },
      patterns[]{
        number,
        title,
        body
      }
    },
    solution{
      intro{
        eyebrow,
        title,
        intro
      },
      pillars[]{
        icon,
        title,
        body
      }
    },
    process{
      intro{
        eyebrow,
        title,
        intro
      },
      steps[]{
        label,
        title,
        points[],
        dark
      },
      ctaText,
      ctaHref
    },
    comparison{
      intro{
        eyebrow,
        title,
        intro
      },
      agencyHeading,
      truvisHeading,
      rows[]{
        agency,
        truvis
      }
    },
    useCases{
      intro{
        eyebrow,
        title,
        intro
      },
      rightTitle,
      notRightTitle,
      rightFor[],
      notFor[]
    },
    deliverables{
      intro{
        eyebrow,
        title,
        intro
      },
      items[]{
        icon,
        title,
        body
      }
    },
    team{
      intro{
        eyebrow,
        title,
        intro
      },
      members[]{
        name,
        role,
        badge,
        points[],
        featured,
        photo{
          alt,
          image
        }
      },
      ctaText,
      ctaHref
    },
    pricing{
      intro{
        eyebrow,
        title,
        intro
      },
      milestones[]{
        pct,
        trigger,
        desc
      },
      packages[]{
        title,
        amount,
        items[],
        accent
      }
    },
    portfolio{
      intro{
        eyebrow,
        title,
        intro
      },
      items[]{
        name,
        category,
        scale,
        relevance,
        logo{
          alt,
          image
        }
      }
    },
    cta{
      eyebrow,
      title,
      description,
      bullets[],
      officeLine,
      formEyebrow,
      formTitle,
      formDescription
    },
    footer{
      companyName,
      tagline,
      motto,
      copyrightPrefix
    }
  }
`
